# Pure nvim, declaratively, drawing its language servers from the closure.
#
# The reasoning that killed LazyVim here: this toolchain declares its LSPs as
# Nix packages (see tools.nix), which BOTH editors consume — nvim natively,
# Zed via PATH discovery — and LazyVim's plugin universe + Mason machinery
# duplicated all of that inside one flavor while a runtime fetcher is exactly
# the thing an airgap cannot afford. nvim 0.11+ ships vim.lsp.config natively,
# so "pure nvim" is ~100 lines of config and the servers come from PATH like
# for Zed. Nothing here reaches the network at runtime: no lazy.nvim clone,
# no :TSInstall compile, no Mason.
{
  lib,
  pkgs,
  config,
  ...
}:
let
  cfg = config.twentyx;

  # The server set nvim enables: canonical nvim config name -> the argv that
  # makes the binary speak LSP. The names are what `vim.lsp.enable` takes (not
  # always the binary name: `bashls`, `yamlls`), and argv is load-bearing --
  # measured failures with a bare command: `ruff` and `taplo` print help and
  # exit, yaml-language-server dies with "Connection input stream is not set".
  # The packages come from nix/modules/lsp.nix (the shared declaration);
  # `package-version-server` is absent on purpose: it is Zed's TOML hover
  # helper, not an nvim server.
  lspServers = {
    basedpyright = [
      "basedpyright-langserver"
      "--stdio"
    ];
    ruff = [
      "ruff"
      "server"
    ];
    nixd = [ "nixd" ];
    bashls = [
      "bash-language-server"
      "start"
    ];
    yamlls = [
      "yaml-language-server"
      "--stdio"
    ];
    taplo = [
      "taplo"
      "lsp"
      "stdio"
    ];
    jsonls = [
      "vscode-json-language-server"
      "--stdio"
    ];
  };

  lspSetup = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (
      name: argv:
      ''  vim.lsp.config["${name}"] = { cmd = { ${lib.concatMapStringsSep ", " (a: ''"${a}"'') argv} } }''
    ) lspServers
  );

  # withAllGrammars is ~1 GB. This curated set is ~40 MB and covers every
  # language in this repo and the ones you actually work in.
  treesitter = pkgs.vimPlugins.nvim-treesitter.withPlugins (
    p: with p; [
      nix
      lua
      python
      bash
      fish
      yaml
      json
      toml
      markdown
      markdown_inline
      dockerfile
      gitcommit
      git_config
      gitignore
      diff
      regex
      vim
      vimdoc
      c
      query
    ]
  );

  initLua = ''
    -- Generated by the airgap flake (nix/modules/nvim.nix). Pure nvim: the
    -- language servers are PATH executables from the Nix closure -- the same
    -- ones Zed uses -- configured with nvim's native vim.lsp API.

    vim.opt.number = true
    vim.opt.relativenumber = true
    vim.opt.expandtab = true
    vim.opt.shiftwidth = 2
    vim.opt.smartindent = true
    vim.opt.termguicolors = true
    vim.opt.signcolumn = "yes"
    vim.opt.updatetime = 250

    -- ── LSP: everything comes from PATH, nothing is downloaded ───────────
    -- The cmd arrays carry the arguments each binary needs; the config names
    -- are nvim's runtime names. See nix/modules/nvim.nix for the measured
    -- failure modes a bare command produces.
${lspSetup}

    -- nixd needs a settings object, otherwise the workspace/configuration
    -- reply is not an object and nixd logs a parse error; nixfmt is shipped.
    vim.lsp.config.nixd.settings = { nixd = { formatting = { command = { "nixfmt" } } } }

    vim.lsp.enable({ ${lib.concatMapStringsSep ", " (n: ''"${n}"'') (lib.attrNames lspServers)} })

    -- Completion is enabled per attaching client. The previous global call
    -- (vim.lsp.completion.enable(true, nil, nil)) throws "invalid client ID"
    -- before any client exists.
    vim.api.nvim_create_autocmd("LspAttach", {
      callback = function(args)
        local client = vim.lsp.get_client_by_id(args.data.client_id)
        if client and client:supports_method("textDocument/completion") then
          vim.lsp.completion.enable(true, client.id, args.buf, { autotrigger = true })
        end

        local map = function(lhs, rhs, desc)
          vim.keymap.set("n", lhs, rhs, { buffer = args.buf })
        end
        map("gd", vim.lsp.buf.definition)
        map("gD", vim.lsp.buf.declaration)
        map("gr", vim.lsp.buf.references)
        map("K", vim.lsp.buf.hover)
        map("<leader>rn", vim.lsp.buf.rename)
        map("<leader>ca", vim.lsp.buf.code_action)
      end,
    })

    vim.diagnostic.config({
      virtual_text = true,
      underline = true,
      signs = true,
      float = { border = "rounded" },
    })

    -- OSC 52 clipboard. In a RunAI pod there is no X11, no Wayland and no
    -- wl-copy, so the escape-sequence path is the only route from a yank in
    -- nvim to the Windows clipboard. tmux passes it through (see shell.nix)
    -- and WezTerm honours it at the far end.
    if vim.env.SSH_TTY or vim.env.KUBERNETES_SERVICE_HOST or vim.env.RUNAI_JOB_NAME then
      vim.g.clipboard = {
        name = "OSC 52",
        copy = {
          ["+"] = require("vim.ui.clipboard.osc52").copy("+"),
          ["*"] = require("vim.ui.clipboard.osc52").copy("*"),
        },
        -- Reading the clipboard over OSC 52 requires the emulator to answer,
        -- which many refuse to do for security. Paste from the terminal
        -- instead; a paste that silently hangs is worse than no paste.
        paste = {
          ["+"] = function() return vim.split(vim.fn.getreg('"'), "\n") end,
          ["*"] = function() return vim.split(vim.fn.getreg('"'), "\n") end,
        },
      }
    end
  '';
in
{
  config = lib.mkIf cfg.nvim.enable {
    # programs.neovim installs the editor itself; no separate home.packages
    # entry -- two neovim derivations in one profile is a buildEnv conflict.
    programs.neovim = {
      enable = true;
      plugins = [ treesitter ];
      initLua = initLua;
      # Headless editor: no ruby/python plugin hosts are ever used (the
      # servers are external binaries from the closure), and the Wayland
      # clipboard is unreachable in a pod. Dropping all three removes the
      # ruby env (~98 MB) and wl-clipboard (~206 MB) from the nvim flavor
      # and from WSL.
      withRuby = false;
      withPython3 = false;
      waylandSupport = false;
    };
  };
}
